on:
  push:
    branches-ignore:
      - "tmp/**"
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go: [1.16]
        node: [15]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - id: yarn-cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}

      - if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn --frozen-lockfile

      - run: go generate ./...

      - name: Run tests
        run: make test

      - name: Build artifacts
        run: make all

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ runner.os }}-dist
          path: bin/
          if-no-files-found: error
